name: testing react project
on:
    push:
        branches:
            - main
jobs:
    testing-react:
        runs-on: ubuntu-latest
        defaults:
                run:
                    working-directory: reactops
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup node environment
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: installing dependencies
              run: npm install
            - name: start the server
              run: npm start