name: testing react project
on:
    push:
        branches:
            - manin
jobs:
    testing-react:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: check node version
              run: node -v