name: Testing context
on: push
env:
    LEVEL: "i am a devops engineer"
jobs:
    testing-variables:
        runs-on: ubuntu-latest
        steps:
            - name: make files available
              uses: actions/checkout@v4

            - name: connecting ssh for testing
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ vars.SSH_KEY }}

            - name: SSh into EC2 instance
              run: |
                ssh -o StrictHostKeyChecking=no -i ./moso_dev.pem ubuntu@ec2-52-206-236-229.compute-1.amazonaws.com "cd ~ && git pull origin main"


