name: Testing context
on: push
env:
    LEVEL: "i am a devops engineer"
jobs:
    testing-variables:
        runs-on: ubuntu-latest
        steps:
            - name: connecting ssh for testing
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_P_KEY }}

            - name: SSh into EC2 instance
              run: |
                ssh -i ${{ secrets.SSH_P_KEY }} ubuntu@ec2-52-206-236-229.compute-1.amazonaws.com "touch worked.txt"


